# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-29 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('uid1', 'uid2')]),
        ),
        migrations.AlterModelTable(
            name='friend',
            table='friend',
        ),
    ]
