# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-01 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200229_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
